{
 "title": "ES Metricbeat - Zookeeper",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "{\"find\": \"terms\", \"field\": \"beat_name.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Packet Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Packet Rate" }
   ],
   "targets": [
    {
     "alias": "Sent Rate",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "packets_sent",
       "hide": true,
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "4",
       "id": "5",
       "meta": {},
       "pipelineAgg": "4",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "WHERE beat_name=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Receive Rate",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "packets_received",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "WHERE beat_name=$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Data Store",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 0 },
   "targets": [
    {
     "alias": "Store Size",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "approximate_data_size",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "WHERE beat_name=$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Counts",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 0 },
   "targets": [
    {
     "alias": "Watch",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "watch_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "WHERE beat_nameE=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Znode",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "znode_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "WHERE beat_nameE=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Ephemerals",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ephemerals_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "WHERE beat_nameE=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Connections",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "num_alive_connections",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "WHERE beat_nameE=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "OUtstanding Requests",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "outstanding_requests",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "WHERE beat_nameE=$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Packets",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 3 },
   "targets": [
    {
     "alias": "Received",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "packets_received",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "WHERE beat_name=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Sent",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "packets_sent",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "WHERE beat_name=$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Latency, Outstanding Requests & Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "alias": "Average Latency",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "latency_avg",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "WHERE bet_name=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Outstanding Requests",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "outstanding_requests",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "WHERE beat_name=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Connections",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "num_alive_connections",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "WHERE beat_name=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Watch Count",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "watch_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "WHERE beat_name=$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 8, "y": 7 },
   "targets": [
    {
     "alias": "Average",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "latency_avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "WHERE beat_name=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Maximum",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "latency_max",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "WHERE beat_name=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Minimum",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "latency_min",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "WHERE beat_name=$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 7 },
   "targets": [
    {
     "alias": "Maximum",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "max_file_descriptor_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "WHERE beat_nameE=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Open",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "open_file_descriptor_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "WHERE beat_nameE=$Node",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}