{
 "title": "ES Metricbeat - Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "{\"find\": \"terms\", \"field\":\"beat_name.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Container Memory Usage",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "memory",
     "bucketAggs": [
      {
       "fake": true,
       "field": "docker_container_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "usage_total",
       "id": "1",
       "inlineScript": "_value / (1024 * 1024)",
       "meta": {},
       "settings": { "script": { "inline": "_value / (1024 * 1024)" } },
       "type": "avg"
      }
     ],
     "query": "beat_name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Docker Containers - Network Out Bytes/min",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "docker_container_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "out_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "beat_name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Docker Containers - Network In Bytes/min",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "docker_container_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "in_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "beat_name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Kibana Requests & Connections",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Requests",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metrics_requests_total",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "WHERE beat_name=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Disconnects",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metrics_requests_disconnects",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "WHERE beat_name=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Connections",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metrics_concurrent_connections",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "WHERE beat_name=$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Docker Containers - Disk IO Writes Bytes/min",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "docker_container_name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "write_bytes",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "beat_name=$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Docker Containers - Disk IO Reads Bytes/min",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "docker_container_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read_bytes",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "4",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "beat_name:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Elasticsearch",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 4 },
   "targets": [
    {
     "alias": "Document Count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "indices_docs_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "beat_name=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Store Size (Mb)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "indices_store_size_bytes",
       "id": "1",
       "inlineScript": "_value / (1024*1024)",
       "meta": {},
       "settings": { "script": { "inline": "_value / (1024*1024)" } },
       "type": "avg"
      }
     ],
     "query": "beat_name=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Space Available (Gb)",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fs_summary_available_bytes",
       "id": "1",
       "inlineScript": "_value / (1024*1024*1024)",
       "meta": {},
       "settings": { "script": { "inline": "_value / (1024*1024*1024)" } },
       "type": "avg"
      }
     ],
     "query": "beat_name=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "JVM Collection Time Old (ms)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm_gc_collectors_old_collection_ms",
       "id": "1",
       "inlineScript": "_value / 1000",
       "meta": {},
       "settings": { "script": { "inline": "_value / 1000" } },
       "type": "avg"
      }
     ],
     "query": "beat_name=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "JVM Collection Count Old",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm_gc_collectors_old_collection_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "beat_name=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "JVM Collection Time Young",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm_gc_collectors_young_collection_ms",
       "id": "1",
       "inlineScript": "_value / 1000",
       "meta": {},
       "settings": { "script": { "inline": "_value / 1000" } },
       "type": "avg"
      }
     ],
     "query": "beat_name=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "JVM Collection Count Young",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm_gc_collectors_young_collection_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "beat_name=$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Zookeeper",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "alias": "Data Size",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "approximate_data_size",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "WHERE beat_name=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Ephemeral Count",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ephemerals_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "WHERE beat_name=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Live Connections",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "num_alive_connections",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "WHERE beat_name=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "File Descriptors",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "open_file_descriptor_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "WHERE beat_name=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Packets Received",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "packets_received",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "WHERE beat_name=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Packets Sent",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "packets_sent",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "WHERE beat_name=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Outstanding Requests",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "outstanding_requests",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "WHERE beat_name=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Watch Count",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "watch_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "WHERE beat_name=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Znode Count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "znode_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "WHERE beat_name=$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "System Processor",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "CPU Total",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "total_pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "WHERE beat_name=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "CPU User",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "user_pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "WHERE beat_name=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "CPU System",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system_pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "WHERE beat_name=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "CPU IO Wait",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "iowait_pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "WHERE beat_name=$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Kafka - Consumergroups Offset Change / min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "id.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "partition",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "offset",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "1",
       "id": "5",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "beat_name:$Node AND NOT(TOPIC_NAME LIKE _*)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Elasticsearch - Segments Count & Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Segments" }
   ],
   "targets": [
    {
     "alias": "Segments",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "indices_segments_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "beat_name=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Segments Memory",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "indices_segments_memory_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "beat_name=$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "System Memory Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percentunit", "label": "percentage" }
   ],
   "targets": [
    {
     "alias": "Menory Used",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "used_pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "WHERE beat_name=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Memory Actual Used",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "actual_used_pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "WHERE beat_name=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Swap Used",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "swap_used_pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "WHERE beat_name=$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Kafka Topic Partitions Offset Newest Change / min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "topic_name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "offset_newest",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "1",
       "id": "5",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "beat_name:$Node AND NOT(TOPIC_NAME LIKE _*)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ElasticSearch JVM - Memory Pools",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Old",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm_mem_pools_old_used_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "beat_name=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Survivor",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm_mem_pools_survivor_used_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "beat_name=$Node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Young",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm_mem_pools_young_used_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "beat_name=$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "System Network Outward",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "decbytes", "label": "percentage" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "out_bytes",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "WHERE beat_name=$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "System Network Inward",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "decbytes", "label": "percentage" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "in_bytes",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "WHERE beat_name=$Node",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}