{
 "title": "ES Metricbeat - Docker Network",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "{\"find\": \"terms\", \"field\": \"BEAT_NAME.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Inward Network Traffic - Bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:8318",
       "fake": true,
       "field": "NETWORK_INTERFACE.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:7276",
       "fake": true,
       "field": "CONTAINER_NAME.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:7277",
       "field": "TIMESTAMP",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:7272",
       "field": "NETWORK_IN_BYTES",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "Outward Network Traffic - Bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:8455",
       "fake": true,
       "field": "NETWORK_INTERFACE.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:7479",
       "fake": true,
       "field": "CONTAINER_NAME.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:7480",
       "field": "TIMESTAMP",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:7475",
       "field": "NETWORK_OUT_BYTES",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "Inward Network Traffic - Packets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:8392",
       "fake": true,
       "field": "NETWORK_INTERFACE.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:7626",
       "fake": true,
       "field": "CONTAINER_NAME.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:7627",
       "field": "TIMESTAMP",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:7622",
       "field": "NETWORK_IN_PACKETS",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:7623",
       "field": "1",
       "hide": true,
       "id": "4",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "Outward Network Traffic - Packets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:8518",
       "fake": true,
       "field": "NETWORK_INTERFACE.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:7773",
       "fake": true,
       "field": "CONTAINER_NAME.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:7774",
       "field": "TIMESTAMP",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:7769",
       "field": "NETWORK_OUT_PACKETS",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "Inward Network Traffic - Errors",
   "type": "graph",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:8592",
       "fake": true,
       "field": "NETWORK_INTERFACE.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:8568",
       "fake": true,
       "field": "CONTAINER_NAME.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:8569",
       "field": "TIMESTAMP",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:8566",
       "field": "NETWORK_IN_ERRORS",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "Outward Network Traffic - Errors",
   "type": "graph",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:8741",
       "fake": true,
       "field": "NETWORK_INTERFACE.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:8717",
       "fake": true,
       "field": "CONTAINER_NAME.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:8718",
       "field": "TIMESTAMP",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:8715",
       "field": "NETWORK_OUT_ERRORS",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "Outward Network Traffic - Dropped Packets",
   "type": "graph",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:8667",
       "fake": true,
       "field": "NETWORK_INTERFACE.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:8643",
       "fake": true,
       "field": "CONTAINER_NAME.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:8644",
       "field": "TIMESTAMP",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:8641",
       "field": "NETWORK_OUT_DROPPED",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "Outward Network Traffic - Dropped Packets",
   "type": "graph",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:8815",
       "fake": true,
       "field": "NETWORK_INTERFACE.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:8791",
       "fake": true,
       "field": "CONTAINER_NAME.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:8792",
       "field": "TIMESTAMP",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:8789",
       "field": "NETWORK_OUT_DROPPED",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "TIMESTAMP"
    }
   ]
  }
 ]
}