{
 "title": "ES Metricbeat - Docker Disk IO",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "{\"find\": \"terms\", \"field\": \"BEAT_NAME.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Disk IO Total Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "CONTAINER_NAME.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "DISKIO_WRITE_BYTES",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "4",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "Disk IO Total Ops Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "CONTAINER_NAME.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "DISKIO_SUMMARY_OPS",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "4",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "Total Data",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "CONTAINER_NAME.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "DISKIO_SUMMARY_BYTES",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "Disk IO Write Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "CONTAINER_NAME.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "DISKIO_WRITE_BYTES",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "4",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "Disk IO Write Ops Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 7 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "CONTAINER_NAME.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "DISKIO_WRITE_OPS",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "4",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "Total Write",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "CONTAINER_NAME.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "DISKIO_WRITE_BYTES",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "Disk IO Read Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "CONTAINER_NAME.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "DISKIO_READ_BYTES",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "4",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "Disk IO Read Ops Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 14 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "CONTAINER_NAME.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "DISKIO_READ_OPS",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "4",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "Total Read",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 14 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "CONTAINER_NAME.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "DISKIO_READ_BYTES",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "TIMESTAMP"
    }
   ]
  }
 ]
}