{
 "title": "ES Metricbeat - System CPU",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "{\"find\": \"terms\", \"field\": \"BEAT_NAME.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "System Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 0 },
   "format": "dtdurationms",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "UPTIME_DURATION_MS",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "CPU User - Per Core",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "CORE_ID",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "CORE_USER_PCT",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "WHERE BEAT_NAME=$Node",
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "LOAD_1",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "BEAT_NAME=$Node",
     "timeField": "TIMESTAMP"
    },
    {
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "LOAD_5",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "BEAT_NAME=$Node",
     "timeField": "TIMESTAMP"
    },
    {
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "LOAD_15",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "BEAT_NAME=$Node",
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "CPU System - Per Core",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "CORE_ID",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "CORE_SYSTEM_PCT",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "WHERE BEAT_NAME=$Node",
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "System CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "CPU_TOTAL_PCT",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "BEAT_NAME=$Node",
     "timeField": "TIMESTAMP"
    },
    {
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "CPU_USER_PCT",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "BEAT_NAME=$Node",
     "timeField": "TIMESTAMP"
    },
    {
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "CPU_IOWAIT_PCT",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "BEAT_NAME=$Node",
     "timeField": "TIMESTAMP"
    },
    {
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "CPU_SOFTIRQ_PCT",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "BEAT_NAME=$Node",
     "timeField": "TIMESTAMP"
    },
    {
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "CPU_SYSTEM_PCT",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "BEAT_NAME=$Node",
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "CPU SoftIRQ - Per Core",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "CORE_ID",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "CORE_SOFTIRQ_PCT",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "WHERE BEAT_NAME=$Node",
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "CPU Total - Per Core",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "CORE_ID",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "CORE_TOTAL_PCT",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "WHERE BEAT_NAME=$Node",
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "CPU IOWait - Per Core",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "CORE_ID",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "CORE_IOWAIT_PCT",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "WHERE BEAT_NAME=$Node",
     "timeField": "TIMESTAMP"
    }
   ]
  }
 ]
}