{
 "title": "ES Metricbeat - Kafka Partitions",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "{\"find\": \"terms\", \"field\": \"BEAT_NAME.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Topic Partitions Publish Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "TOPIC_NAME.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "PARTITION_OFFSET_NEWEST",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "5",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "WHERE BEAT_NAME=$Node AND NOT (TOPIC_NAME LIKE _*)",
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "Topic Partitions Max Offset",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 10, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "TOPIC_NAME.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "PARTITION_OFFSET_NEWEST",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "WHERE BEAT_NAME=$Node",
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "Kafka Partitions Publish Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "TOPIC_NAME.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "PARTITION_OFFSET_NEWEST",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "1",
       "id": "5",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "WHERE BEAT_NAME=$Node AND (TOPIC_NAME LIKE _*)",
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "Topic Partitions Min Offset",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 10, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "TOPIC_NAME.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "PARTITION_OFFSET_OLDEST",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "WHERE BEAT_NAME=$Node",
     "timeField": "TIMESTAMP"
    }
   ]
  }
 ]
}