{
 "title": "ES Metricbeat - Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "{\"find\": \"terms\", \"field\":\"BEAT_NAME.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Container Memory Usage",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "memory",
     "bucketAggs": [
      {
       "fake": true,
       "field": "CONTAINER_NAME.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "MEMORY_USAGE_TOTAL",
       "id": "1",
       "inlineScript": "_value / (1024 * 1024)",
       "meta": {},
       "settings": { "script": { "inline": "_value / (1024 * 1024)" } },
       "type": "max"
      }
     ],
     "query": "BEAT_NAME:$Node",
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "Docker Containers - Network Out Bytes/min",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "CONTAINER_NAME.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "NETWORK_OUT_BYTES",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "BEAT_NAME:$Node",
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "Docker Containers - Network In Bytes/min",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "CONTAINER_NAME.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "NETWORK_IN_BYTES",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "BEAT_NAME:$Node",
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "Kibana Requests & Connections",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Requests",
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "REQUEST_TOTAL",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "BEAT_NAME:$Node",
     "timeField": "TIMESTAMP"
    },
    {
     "alias": "Disconnects",
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "REQUEST_DISCONNECTS",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "BEAT_NAME:$Node",
     "timeField": "TIMESTAMP"
    },
    {
     "alias": "Connections",
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "CONCURRENT_CONNECTIONS",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "BEAT_NAME:$Node",
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "Docker Containers - Disk IO Writes Bytes/min",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "CONTAINER_NAME.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "DISKIO_WRITE_BYTES",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "BEAT_NAME=$Node",
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "Docker Containers - Disk IO Reads Bytes/min",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "CONTAINER_NAME.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "DISKIO_READ_BYTES",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "4",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "BEAT_NAME:$Node",
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "Elasticsearch",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 4 },
   "targets": [
    {
     "alias": "Document Count",
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "INDICES_DOCS_COUNT",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "BEAT_NAME:$Node",
     "timeField": "TIMESTAMP"
    },
    {
     "alias": "Store Size (Mb)",
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "INDICES_STORE_SIZE",
       "id": "1",
       "inlineScript": "_value / (1024*1024)",
       "meta": {},
       "settings": { "script": { "inline": "_value / (1024*1024)" } },
       "type": "avg"
      }
     ],
     "query": "BEAT_NAME:$Node",
     "timeField": "TIMESTAMP"
    },
    {
     "alias": "Space Available (Gb)",
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "FS_AVAILABLE",
       "id": "1",
       "inlineScript": "_value / (1024*1024*1024)",
       "meta": {},
       "settings": { "script": { "inline": "_value / (1024*1024*1024)" } },
       "type": "avg"
      }
     ],
     "query": "BEAT_NAME:$Node",
     "timeField": "TIMESTAMP"
    },
    {
     "alias": "JVM Collection Time Old (ms)",
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "JVM_GC_OLD_COLLECTION_MS",
       "id": "1",
       "inlineScript": "_value / 1000",
       "meta": {},
       "settings": { "script": { "inline": "_value / 1000" } },
       "type": "avg"
      }
     ],
     "query": "BEAT_NAME:$Node",
     "timeField": "TIMESTAMP"
    },
    {
     "alias": "JVM Collection Count Old",
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "JVM_GC_OLD_COLLECTION_COUNT",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "BEAT_NAME:$Node",
     "timeField": "TIMESTAMP"
    },
    {
     "alias": "JVM Collection Time Young",
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "JVM_GC_YOUNG_COLLECTION_MS",
       "id": "1",
       "inlineScript": "_value / 1000",
       "meta": {},
       "settings": { "script": { "inline": "_value / 1000" } },
       "type": "avg"
      }
     ],
     "query": "BEAT_NAME:$Node",
     "timeField": "TIMESTAMP"
    },
    {
     "alias": "JVM Collection Count Young",
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "JVM_GC_YOUNG_COLLECTION_COUNT",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "BEAT_NAME:$Node",
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "Zookeeper",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "alias": "Data Size",
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "APPROXIMATE_DATA_SIZE",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "BEAT_NAME:$Node",
     "timeField": "TIMESTAMP"
    },
    {
     "alias": "Ephemeral Count",
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "EPHEMERALS_COUNT",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "BEAT_NAME:$Node",
     "timeField": "TIMESTAMP"
    },
    {
     "alias": "Live Connections",
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "NUM_ALIVE_CONNECTIONS",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "BEAT_NAME:$Node",
     "timeField": "TIMESTAMP"
    },
    {
     "alias": "File Descriptors",
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "OPEN_FILE_DESCRIPTOR_COUNT",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "BEAT_NAME:$Node",
     "timeField": "TIMESTAMP"
    },
    {
     "alias": "Packets Received",
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "PACKETS_RECEIVED",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "BEAT_NAME:$Node",
     "timeField": "TIMESTAMP"
    },
    {
     "alias": "Packets Sent",
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "PACKETS_SENT",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "BEAT_NAME:$Node",
     "timeField": "TIMESTAMP"
    },
    {
     "alias": "Outstanding Requests",
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "OUTSTANDING_REQUESTS",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "BEAT_NAME:$Node",
     "timeField": "TIMESTAMP"
    },
    {
     "alias": "Watch Count",
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "WATCH_COUNT",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "BEAT_NAME:$Node",
     "timeField": "TIMESTAMP"
    },
    {
     "alias": "Znode Count",
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ZNODE_COUNT",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "BEAT_NAME:$Node",
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "System Processor",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "CPU Total",
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "CPU_TOTAL_PCT",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "BEAT_NAME:$Node",
     "timeField": "TIMESTAMP"
    },
    {
     "alias": "CPU User",
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "CPU_USER_PCT",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "BEAT_NAME:$Node",
     "timeField": "TIMESTAMP"
    },
    {
     "alias": "CPU System",
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "CPU_SYSTEM_PCT",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "BEAT_NAME:$Node",
     "timeField": "TIMESTAMP"
    },
    {
     "alias": "CPU IO Wait",
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "CPU_IOWAIT_PCT",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "BEAT_NAME:$Node",
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "Kafka - Consumergroups Offset Change / min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "CONSUMERGROUP_ID.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "CONSUMERGROUP_PARTITION",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "CONSUMERGROUP_OFFSET",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "1",
       "id": "5",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "BEAT_NAME:$Node AND NOT(TOPIC_NAME LIKE _*)",
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "Elasticsearch - Segments Count & Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Segments" }
   ],
   "targets": [
    {
     "alias": "Segments",
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "INDICES_SEGMENTS_COUNT",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "BEAT_NAME$Node",
     "timeField": "TIMESTAMP"
    },
    {
     "alias": "Segments Memory",
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "INDICES_SEGMENTS_MEMORY",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "BEAT_NAME$Node",
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "System Memory Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percentunit", "label": "percentage" }
   ],
   "targets": [
    {
     "alias": "Menory Used",
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "MEMORY_USED_PCT",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "BEAT_NAME:$Node",
     "timeField": "TIMESTAMP"
    },
    {
     "alias": "Memory Actual Used",
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "MEMORY_ACTUAL_USED_PCT",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "BEAT_NAME:$Node",
     "timeField": "TIMESTAMP"
    },
    {
     "alias": "Swap Used",
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "MEMORY_SWAP_USED_PCT",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "Kafka Topic Partitions Offset Newest Change / min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "TOPIC_NAME.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "PARTITION_OFFSET_NEWEST",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "1",
       "id": "5",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "BEAT_NAME:$Node AND NOT(TOPIC_NAME LIKE _*)",
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "ElasticSearch JVM - Memory Pools",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Old",
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "JVM_POOLS_OLD_USED",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "BEAT_NAME:$Node",
     "timeField": "TIMESTAMP"
    },
    {
     "alias": "Survivor",
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "JVM_POOLS_SURVIVOR_USED",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "BEAT_NAME:$Node",
     "timeField": "TIMESTAMP"
    },
    {
     "alias": "Young",
     "bucketAggs": [
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "JVM_POOLS_YOUNG_USED",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "BEAT_NAME:$Node",
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "System Network Outward",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "decbytes", "label": "percentage" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "NETWORK_NAME.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "NETWORK_OUT_BYTES",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "BEAT_NAME:$Node",
     "timeField": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "System Network Inward",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "decbytes", "label": "percentage" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "NETWORK_NAME.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "TIMESTAMP", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "NETWORK_IN_BYTES",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "BEAT_NAME:$Node",
     "timeField": "TIMESTAMP"
    }
   ]
  }
 ]
}