FROM confluentinc/cp-enterprise-kafka:4.1.0

COPY ./log4j.properties.template /etc/confluent/docker/log4j.properties.template
COPY ./tools-log4j.properties.template /etc/confluent/docker/tools-log4j.properties.template


